site_name: McRUN System Documentation
site_description: Documentation for the McRUN System, including McRace Code and user guides.
site_author: McGill Student Running Club (Tech Team)
#repo_name: mcrace code
#repo_url: https://github.com/mcrunningclub/mcrace-code.git
copyright: Copyright &copy; 2025 McGill Student Running Club - <a href="#__consent">Cookies Preference</a>

nav:
  - Home: index.md

  - Getting Started:
      - Setup: start/setup.md
      - Contributing:
        - mkdocs: start/getting-started.md
        - Syntax: start/syntax.md
        - Code Examples: start/code-examples.md
      - FAQ: start/faq.md

  - Project: 
      - Overview: projects/projects.md
      
      - Membership Code: 
        - Registry: projects/membership-list-code.md
        - Communications: projects/new-member-communications-code.md
      
      - Attendance Code:
        - Semester: projects/attendance-semester-code.md
        - Semester (old): projects/attendance-code-old.md
        - Master: projects/attendance-master-code.md
      
      - Points System Code: 
        - Ledger: projects/points-system-code.md
        - Points Email: projects/points-email-code.md

      - Other:
        - McRace Code: projects/mcrace-code.md

theme:
  name: material
  logo: assets/mcrun-logo-circle.png
  favicon: assets/mcrun-favicon.png

  palette:
  # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  font:
    text: Inter
    code: Red Hat Mono

  features:
    - content.code.copy
    - content.code.select

    - navigation.footer
    - navigation.top
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.sections
    - navigation.path
    - navigation.indexes

    - toc.follow
    # - toc.integrate


extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list

  - toc:
      permalink: true
      toc_depth: 3

  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  
  - admonition

  - pymdownx.details
  
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  
  - pymdownx.inlinehilite
  
  - pymdownx.snippets
  
  - pymdownx.superfences

  # - material.extensions.preview:
  #     configurations:
  #       - targets:
  #           include:
  #             - projects/mcrun-code.md

# plugins:
#   - git-revision-date-localized:
#       enable_creation_date: true
#       fallback_to_build_date: true
#       include_build_date: true
#       include_git_hash: true
#       git_hash_format: short

#   - git-committers:
#       repository: squidfunk/mkdocs-material
#       branch: master
#       committers:
#         - name: AndreyG

#   - git-authors

extra:
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:<mcrunningclub@ssmu.ca>
    - icon: fontawesome/brands/github
      link: https://github.com/mcrunningclub
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/mcgillstudentsrunningclub/

  version:
    provider: mike
