site_name: McRUN System Documentation
site_description: Documentation for the McRUN System, including McRace Code and user guides.
site_author: McGill Student Running Club (Tech Team)
site_url: https://mcrunningclub.github.io/mcrun-system/
repo_url: https://github.com/mcrunningclub/mcrun-system
repo_name: mcrun-system
copyright: Copyright &copy; 2026 McGill Student Running Club

nav:
  - Home:
      - Home: index.md
  - Getting Started:
      - Overview: start/index.md
      - Google Apps Scripts: start/gas.md
      - FAQ: start/faq.md
  - User Guide:
      - Overview: users/index.md
  - Developer Guide:
      - Overview: developers/index.md
      - Contributing: developers/contributing-code.md
      - Contributing to the documentation: developers/contributing-docs.md
      - Formatting the documentation: developers/formatting.md
  - Projects:
      - Overview: projects/index.md
      - Membership Code:
          - Membership List: projects/membership/registry.md
          - New Member Communications: projects/membership/communications.md
      - Attendance Code:
          - Master Attendance: projects/attendance/master.md
          - Semester Attendance: projects/attendance/semester.md
      - Points System Code:
          - Points Ledger: projects/points/ledger.md
      - McRace Code:
          - Registrations: projects/mcrace/registry.md
          - Cross Referencing: projects/mcrace/crossref.md
          - Timing System: projects/mcrace/timing.md

theme:
  language: en
  name: material
  logo: assets/mcrun-logo.png
  favicon: assets/mcrun-favicon.png
  palette:
    primary: custom
    accent: custom
  font:
    text: Figtree
    code: JetBrains Mono
  features:
    - content.code.copy
    - content.code.select
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.sections
    - navigation.path
    - navigation.prune
    - navigation.top
    - toc.follow
    - header.autohide

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: docs_snippets/
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:<mcrunningclub@ssmu.ca>
    - icon: fontawesome/brands/github
      link: https://github.com/mcrunningclub
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/mcrun.mcgill
