authors:
  andrey:
    name: Andrey Gonzalez
    description: VP Operations
    avatar: https://avatars.githubusercontent.com/u/6908294
    # url: https://www.youtube.com/@james-willett?sub_confirmation=1

  mona:
    name: Mona Liu
    description: Tech Assistant
    avatar: https://avatars.githubusercontent.com/u/12345678