authors:
  andrey:
    name: Andrey Gonzalez
    description: VP Operations
    avatar: https://avatars.githubusercontent.com/u/98128637?v=4
    # url: https://www.youtube.com/@james-willett?sub_confirmation=1

  mona:
    name: Mona Liu
    description: Tech Assistant
    avatar: https://avatars.githubusercontent.com/u/48808581?v=4
