authors:
  andrey:
    name: Andrey Gonzalez
    description: VP Operations
    avatar: https://avatars.githubusercontent.com/u/98128637?v=4
    # url: https://www.youtube.com/@james-willett?sub_confirmation=1

  areebah:
    name: Areebah Farid
    description: Tech Assistant
    avatar: https://avatars.githubusercontent.com/u/159209558?s=96&v=4

  emilei:
    name: Emilei Lu
    description: Tech Assistant
    avatar: https://avatars.githubusercontent.com/u/212982553?s=96&v=4

  lilan:
    name: Lilan Forsyth
    description: Tech Assistant
    avatar: https://avatars.githubusercontent.com/u/99054048?s=96&v=4

  mona:
    name: Mona Liu
    description: Tech Assistant
    avatar: https://avatars.githubusercontent.com/u/48808581?v=4

  oscar:
    name: Oscar Tesniere
    description: Tech Assistant
    avatar: https://avatars.githubusercontent.com/u/116503103?s=96&v=4